export const homeObjOne = { 
    id: 'project',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Project1',
    headline: 'Personal Portfolio',
    description: 'Built my personal portfolio website. Using HTML, CSS, React, styled-components.',
    html5:require('../img/html-5.svg'),
    css3:require('../img/css3.svg'),
    javascript:require('../img/javascript.svg'),
    react:require('../img/react.svg'),
    materialui:require('../img/material-ui.svg'),
    firebase:require('../img/firebase.svg'),
    buttonLabel1: 'Live Site',
    buttonLabel2: 'GitHub Rep',
    imgStart: false,
    img: require('../img/portfolio.png'),
    alt: 'portfolio',
    dark: true,
    primary: true,
    darkText: false
}

export const homeObjTwo = { 
    id: 'project2',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Project 2',
    headline: 'Twitter Clone',
    description: 'Built a clone of the Twitter homepage.',
    html5:require('../img/html-5.svg'),
    css3:require('../img/css3.svg'),
    javascript:require('../img/javascript.svg'),
    react:require('../img/react.svg'),
    materialui:require('../img/material-ui.svg'),
    firebase:require('../img/firebase.svg'),
    buttonLabel1: 'Live Site',
    buttonLabel2: 'GitHub Rep',
    imgStart: true,
    img: require('../img/twitter-clone.png'),
    alt: 'portfolio',
    dark: false,
    primary: false,
    darkText: true
}

export const homeObjThree = { 
    id: 'project3',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Project 3',
    headline: 'Telsa Clone',
    description: 'Built a tesla landing page clone.',
    html5:require('../img/html-5.svg'),
    css3:require('../img/css3.svg'),
    javascript:require('../img/javascript.svg'),
    react:require('../img/react.svg'),
    materialui:require('../img/material-ui.svg'),
    firebase:require('../img/firebase.svg'),
    buttonLabel1: 'Live Site',
    buttonLabel2: 'GitHub Rep',

    imgStart: false,
    img: require('../img/tesla-clone.png'),
    alt: 'portfolio',
    dark: true,
    primary: true,
    darkText: false
}